export const MESSAGE_SUPPORT_ATTACKER = "MESSAGE_SUPPORT_ATTACKER";
export const MESSAGE_RECEIVE_BALL = "MESSAGE_RECEIVE_BALL";
export const MESSAGE_PASS_TO_ME = "MESSAGE_PASS_TO_ME";
export const MESSAGE_GO_HOME = "MESSAGE_GO_HOME";
export const MESSAGE_WAIT = "MESSAGE_WAIT";
