const DRAG = 0.975;
const TIME_DELTA = 1000 / 60;
const MAX_SHOT_POWER = 500;
const MAX_PASS_POWER = 350;
const POT_SHOT_CHANCE = 0.05;
const PASS_THREAT_RADIUS = 70;

export {
  DRAG,
  TIME_DELTA,
  MAX_SHOT_POWER,
  MAX_PASS_POWER,
  POT_SHOT_CHANCE,
  PASS_THREAT_RADIUS,
};
