const DRAG = 0.975;
const TIME_DELTA = 1 / 60;
const TIME_DELTA_MILI = TIME_DELTA * 1000;
const MAX_SHOT_POWER = 750;
const MAX_PASS_POWER = 500;
const POT_SHOT_CHANCE = 0.005;
const PASS_THREAT_RADIUS = 70;
const MIN_PASS_DISTANCE = 100;
const RECEIVING_RANGE = 50;
const KICKING_RANGE = 16;
const PLAYER_COMFORT_DISTANCE = 100;

export {
  DRAG,
  TIME_DELTA,
  TIME_DELTA_MILI,
  MAX_SHOT_POWER,
  MAX_PASS_POWER,
  POT_SHOT_CHANCE,
  PASS_THREAT_RADIUS,
  MIN_PASS_DISTANCE,
  RECEIVING_RANGE,
  KICKING_RANGE,
  PLAYER_COMFORT_DISTANCE,
};
