import { PlayerProps } from "../types";

export const players: PlayerProps[] = [
  {
    id: 1,
    name: "Player",
    role: "GK",
    speed: 3.5,
    strength: 1,
    power: 1,
    toughness: 1,
    accuracy: 1,
  },
  {
    id: 2,
    name: "Player",
    role: "DF",
    speed: 3.5,
    strength: 1,
    power: 1,
    toughness: 1,
    accuracy: 1,
  },
  {
    id: 3,
    name: "Player",
    role: "DF",
    speed: 3.5,
    strength: 1,
    power: 1,
    toughness: 1,
    accuracy: 1,
  },
  {
    id: 4,
    name: "Player",
    role: "AT",
    speed: 3.5,
    strength: 1,
    power: 1,
    toughness: 1,
    accuracy: 1,
  },
  {
    id: 5,
    name: "Player",
    role: "AT",
    speed: 3.5,
    strength: 1,
    power: 1,
    toughness: 1,
    accuracy: 1,
  },
];
